version: '3'
services:
  package-capturer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-package-capturer
    command: python server.py -i eth0 -p 80
    volumes:
      - ".:/code"
    network_mode: "container:dfjk_fuel_server"
    container_name: dfjk_fuel_debug
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-frontend
    volumes:
      - "./front_end:/usr/share/nginx/html"
    ports:
      - "4030:80"
networks:
  default:
    external:
      name: fuel
