version: '3'
services:
  package-capturer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-package-capturer
    command: python server.py -i eth0 -p 4020
    volumes:
      - ".:/code"
    ports:
      - "4061:14061"
    network_mode: "host"
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-frontend
    volumes:
      - "./front_end:/usr/share/nginx/html"
    ports:
      - "4062:80"
networks:
  default:
    external:
      name: fuel
