FROM python:3.6
LABEL version=0.1
RUN apt-get update && \
    apt-get install -y tcpdump tcpflow
ADD . /code
WORKDIR /code
ENV PYTHONPATH .
RUN pip install -r requirements.txt --index-url=https://pypi.douban.com/simple \
    --trusted-host=pypi.douban.com
